version: "2" 
services: 
###########################################
###### Clinical data Workflow        ######
###########################################
  data_postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
  rdf_store:
    image: jvsoest/graphdb-free:fairstation
    ports: 
      - "7200:7200"
    environment:
      - GDB_HEAP_SIZE=2g
      - GDB_MIN_MEM=1g
      - GDB_MAX_MEM=2g
  r2rml:
    image: jvsoest/r2rml
    links:
      - data_postgres:dbhost
      - rdf_store:graphdb
  notebook:
    image: jvsoest/notebook:pbdw
    ports:
      - "8888:8888"
      - "8088:8088"
    volumes:
      - ./notebooks:/queries/
    links:
      - data_postgres:postgresdb
      - rdf_store:graphdb
  oraw:
    image: jvsoest/oraw
    volumes:
      - ./dicom/:/data/
    links:
      - rdf_store:graphdb
    environment:
      - RDF4J_URL=http://graphdb:7200
      - EXCLUDE_STRUCTURE_REGEX="(Patient.*|BODY.*|Body.*|NS.*|Couch.*|Isocenter.*)"
###########################################################
# Dummy containers already downloaded for convenience
###########################################################
#  dummy_download_matlab_code:
#    image: jvsoest/svm_site
###########################################################
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  192.169.230.1/24
