PREFIX roo: <http://www.cancerdata.org/roo/>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
SELECT ?id ?genderValue ?tnmTLocal ?tnmNLocal
WHERE {
   ?patient a ncit:C16960 .
   
   OPTIONAL {
       ?patient roo:P100018 ?gender .
       ?gender roo:local_value ?genderValue .
   }
    
   ?patient roo:P100008 ?disease.
   
   OPTIONAL {
       ?disease roo:P100243 ?tnmStage.
       ?tnmStage roo:P100244 ?tnmT.
       ?tnmT roo:local_value ?tnmTLocal.
       OPTIONAL {
           ?tnmStage roo:P100242 ?tnmN.
           ?tnmN roo:local_value ?tnmNLocal.
       }
   }
}